### ISSUE TITLE
我在客户端看到了重试的代码，重试代码放在客户端做，高并发如何保证数据的一致性？

### ISSUE THREAD

**Issue by chengyu3075** [vesoft-inc/nebula-java#100]
int retry = executionRetry;
        while (retry-- > 0) {
            try {
                ExecutionResponse executionResponse = client.execute(sessionID, statement);
                if (executionResponse.getError_code() != ErrorCode.SUCCEEDED) {
                    LOGGER.error("execute error: " + executionResponse.getError_msg());
                }
                return executionResponse.getError_code();
            } catch (TException e) {
                LOGGER.error("Thrift rpc call failed: " + e.getMessage());
                return ErrorCode.E_RPC_FAILURE;
            }
        }

**Comment by darionyaphet** [comment]
这个主要是用来防止在压力比较大的时候 出现请求失败 高并发环境数据一致性和这个没关系吧
