### ISSUE TITLE
I have three graphd processes，and I use the java client to connect nebula,when I shutdown one process,errors occurs on the client like below?

### ISSUE THREAD

**Issue by chengyu3075** [vesoft-inc/nebula-java#103]
c.v.nebula.client.graph.GraphClientImpl  : Thrift rpc call failed: java.net.SocketException: Software caused connection abort: socket write error

**Comment by darionyaphet** [comment]
Seems the connection create failed and you can retry.

**Comment by chenxu14** [comment]
I think there needs a feature to support graphd failover, since the graphd are stateless.

**Comment by klay-ke** [comment]
closed since failover is supported in v2.0
