### ISSUE TITLE
Why using ThreadLocal<GraphService.Client> in GraphClientImpl?

### ISSUE THREAD

**Issue by RaulGuo** [vesoft-inc/nebula-java#171]
In the GraphClientImpl.java, I noticed that the "client" field is used to execute the real query is using the following way:
```
public class GraphClientImpl extends AbstractClient implements GraphClient {
    // the real thrift client is wrapped in a ThreadLocal
    private ThreadLocal<GraphService.Client> client = new ThreadLocal<>();
    @Override
    public int doConnect(List<HostAndPort> addresses) throws TException {
        GraphService.Client thriftClient = new GraphService.Client(protocol);
        client.set(thriftClient);
    }
```
This works well when the GraphClientImpl object is used within the same thread that create it, but if I create a new Thread, and use this GraphClientImpl object within the new thread, I cannot get the GraphService.client using the ThreadLocal.
```
GraphClient graphClient = new GraphClientImpl(addresses);
// this works well
graphClient.executeQuery(gql);

// this doesn't work because in new thread, graphClient cannot get the real thriftClient using ThreadLocal
new Thread(() -> {
        graphClient.executeQuery(gql);
    }).start();
```

I have two questions about this:
1. Why using ThreadLocal to wrap the GraphService.Client? Is it to achieve multi-thread safe? If we don't use ThreadLocal, where there will be trouble?
2. Is there a better way to do this? In this way, the thread that want to use GraphClientImpl object must be the thread that create this object, it is very inconvenient and easy to make mistakes.

Thanks for any help.

**Comment by Nicole00** [comment]
Thanks for your attention to nebula java client. 
1. We used ThreadLocal to achieve thread safe, in case the executions are disorderly. If we share a client in different threads, the "use space" execution will cause that all operations in other threads are executed on this space.
2. Your code lost the connect() operation, and your first executeQuery operation will throw ConnectionException("hrift rpc call failed")
The GraphClient's usage is:
```
GraphClient graphClient = new GraphClientImpl(addresses);
graphClient.connect();
graphClient.executeQuery(gql);

new Thread(() -> {
        graphClient.connect();
        graphClient.executeQuery(gql);
    }).start();
```

**Comment by RaulGuo** [comment]
@Nicole00 Thank you for your reply. So, for question one, if I can guarante in my application that differenct thread using the same thriftClient will execute with no switch space operation, I can use thriftClient across multi thread, right?

**Comment by Nicole00** [comment]
> use thriftClient across multi thread, right

Yeah，and please guarantee that your client is connected before any execution.
