### ISSUE TITLE
为什么通过spark connector reader会读出重复的节点和边？

### ISSUE THREAD

**Issue by ericxluo** [vesoft-inc/nebula-java#189]
我通过自行构造SST文件，并调用`ingest tag/edge`命令来将其导入nebula，然后使用spark connector reader读取它们
导入时总计3000万个节点，读取时会读出10亿+的节点，最多的节点会出现200+条重复的记录，这些重复的记录的vertexID和其他属性完全相同
边的话则会更多，暂时还没有统计，因为我光统计读取到的数量就需要花费很长的时间。。
不知道是什么原因？

除了spark connector reader之外还有什么其他合适的统计nebula节点数量的方式么？我现在不清楚是哪一步出了问题

**Comment by Nicole00** [comment]
可以使用db_dump工具统计图中节点数量，db_dump使用手册 -> https://docs.nebula-graph.com.cn/manual-CN/3.build-develop-and-administration/5.storage-service-administration/data-export/dump-tool/

麻烦你贴一下使用spark-connector的代码吧，看下配置参数

**Comment by ericxluo** [comment]
使用spark-connector的代码其实很简单。。大概这样
```
val df = spark.read.nebula("ip1:port1,ip2:port2", "space_xx", "255").loadVerticesToDF("tag_xx", "*")
  // 将节点ID从string转为Long，在我的后续其他逻辑中会被用到
  .withColumn("_vertexId", $"_vertexId".cast(LongType))
df.count // 大概会读出10亿+节点
df.dropDuplicates("_vertexId").count // 通过该字段去重后会只剩下3000万
```
（由于是公司内使用的代码，我不得不省略具体的地址信息。。）

db_dump看起来是需要直接去nebula的机器上执行？而且似乎还需要暂时停止实例？
由于我使用的nebula是另一个团队提供的大家共同使用的测试实例，所以不太方便做这个。。
或者有没有方法能确认某个指定id的节点在nebula中的实际数量？我看scan命令会查出该节点的版本号，不过只显示最新的版本，不知道有没有可能扫出隐藏的其他版本，有点类似hbase中的raw scan

**Comment by Nicole00** [comment]
1. db_dump是要在服务所在节点执行，但不影响使用，您说的停止实例是指？
2.  关于数据的多版本，需要看下nebula的配置，有没有开启多版本功能，但你说的200+相同vid的数据应该不是多版本的问题。

**Comment by Nicole00** [comment]
Thanks for your usage and discovering problem, the problem has been fixed by PR #190 , please pull the code again.

**Comment by ericxluo** [comment]
使用新的代码已经没有我说的这个问题了，非常感谢！Nice work~
