### ISSUE TITLE
Where is flink connector？

### ISSUE THREAD

**Issue by f7753** [vesoft-inc/nebula-java#220]
Refer to  this article: https://nebula-graph.com.cn/posts/nebula-flink-connector/
it seems that there should be a flink connector code base and example, but until now, I could not find any relative code.

So where it is?

Looking forward to this feature.

**Comment by oldLady344** [comment]
Hi f7753, you can find it in the v1.0 branch. Here is the link: https://github.com/vesoft-inc/nebula-java/tree/v1.0/tools

Thank you.

**Comment by f7753** [comment]
Roger that，thanks :)
