### ISSUE TITLE
Please upgrade the version of guava

### ISSUE THREAD

**Issue by shuitai** [vesoft-inc/nebula-java#242]
Please upgrade the version of guava, the guava is too old, there will be conflictions with new guava version.

**Comment by Nicole00** [comment]
Please see PR  #241

**Comment by shuitai** [comment]
Have you rolled out it to the maven repo？

**Comment by Nicole00** [comment]
> Have you rolled out it to the maven repo？

Not yet. We will publish it with the next minor version.
