### ISSUE TITLE
please push new version of 1.x branch  to maven 

### ISSUE THREAD

**Issue by xrfinbupt** [vesoft-inc/nebula-java#255]
the branch https://github.com/vesoft-inc/nebula-java/tree/v1.0 is new
but the https://mvnrepository.com/artifact/com.vesoft/nebula/1.1.0 is too old

**Comment by Nicole00** [comment]
We'll push new version for client when new feature is added. The new feature is reading schema only from leader.

**Comment by Nicole00** [comment]
https://repo1.maven.org/maven2/com/vesoft/client/1.2.0/
