### ISSUE TITLE
log conflict

### ISSUE THREAD

**Issue by caorong** [vesoft-inc/nebula-java#257]
nubula force binding slf4j with log4j, if I use logback， will be conflict

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/xx/.m2/repository/com/vesoft/client/1.1.0/client-1.1.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/xx/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
```

nebula java api shaded log, guava, thrift dep but not change their package name, this is a bad practice, will cause developer dependency conflict

**Comment by Nicole00** [comment]
explode the slf4j dependency and reimport another slf4j version resolve your problem？

**Comment by Nicole00** [comment]
the current client just depends on log API, do not include the implementation of slf4j. Users can reimport logback or log4j to use the log implementation by themselves.
