### ISSUE TITLE
partitionID with negative number

### ISSUE THREAD

**Issue by zekisong** [vesoft-inc/nebula-java#259]
function edgeKey & vertexKey in NebulaCodecImpl.java

     long hash = MurmurHash2.hash64(vertexId.getBytes(), vertexId.length(), SEEK);
     int partitionId = (int) (hash % getPartSize(spaceName) + 1);
     
    maybe we will get negative partitionID, but we expect 1 to partition_size range

**Comment by laura-ding** [comment]
> ```
> function edgeKey & vertexKey in NebulaCodecImpl.java
> 
>  long hash = MurmurHash2.hash64(vertexId.getBytes(), vertexId.length(), SEEK);
>  int partitionId = (int) (hash % getPartSize(spaceName) + 1);
>  
> maybe we will get negative partitionID, but we expect 1 to partition_size range
> ```

https://github.com/vesoft-inc/nebula-java/pull/258 has solved it

**Comment by zekisong** [comment]
ok, thank you! @laura-ding
