### ISSUE TITLE
maven中无法下载v2.0版本的nebula

### ISSUE THREAD

**Issue by xupengjun** [vesoft-inc/nebula-java#264]
在maven中找到依赖，准备使用时，发现maven仓库中的<type>pom</type>,项目中无法使用它的jar包
![image](https://user-images.githubusercontent.com/20333917/109899292-9a60a980-7cd0-11eb-886a-257aaa90ecfe.png)

在官网中按照要求使用依赖时，也无法依赖成功
![image](https://user-images.githubusercontent.com/20333917/109899329-a8aec580-7cd0-11eb-8725-7b5afc775d65.png)
![image](https://user-images.githubusercontent.com/20333917/109899408-ca0fb180-7cd0-11eb-8bff-89dab4c1f3a3.png)

**Comment by laura-ding** [comment]
Sorry, SNAPSHOT is not uploaded to Maven, it is only the master version.
