### ISSUE TITLE
How to use Nebula Graph Exchange in Nebula Graph v2.0

### ISSUE THREAD

**Issue by JArma19** [vesoft-inc/nebula-java#289]
I was trying to import data from neo4j to Nebula Graph v2.0. 
I found that I need Nebula Graph Exchange, but in nebula-java v2.0 branch there's no "tools" directory, so I was wondering how I can  perform my task. Could you please help me how to do it (admitting that it's possible)?

**Comment by Nicole00** [comment]
Here is Exchange2.0  https://github.com/vesoft-inc/nebula-spark-utils/tree/master/nebula-exchange
