### ISSUE TITLE
Java tools for nebula version 2.0.0

### ISSUE THREAD

**Issue by herman72** [vesoft-inc/nebula-java#299]
I want to use nebula algorithm such as pagerank on database, but apparently is that correct? How can I use those algorithm on nebula version 2?

**Comment by wey-gu** [comment]
Dear @herman72 ,

Please check here https://github.com/vesoft-inc/nebula-spark-utils/tree/master/nebula-algorithm

Thanks!

**Comment by herman72** [comment]
> Dear @herman72 ,
> 
> Please check here https://github.com/vesoft-inc/nebula-spark-utils/tree/master/nebula-algorithm
> 
> Due to it was released last week, the English version of documentation is not yet ready, we are working on that.
> 
> Thanks!

Thanks,

**Comment by wey-gu** [comment]
> > Dear @herman72 ,
> > Please check here https://github.com/vesoft-inc/nebula-spark-utils/tree/master/nebula-algorithm
> > Due to it was released last week, the English version of the documentation is not yet ready, we are working on that.
> > Thanks!
> 
> Thanks,

I quickly translated one here https://github.com/wey-gu/nebula-spark-utils/tree/master/nebula-algorithm, we are working on it to make it polished in English.
Thanks.

**Comment by wey-gu** [comment]
Dear @herman72,
Now, https://github.com/vesoft-inc/nebula-spark-utils/tree/master/nebula-algorithm is all English :-).
Thanks ;-)

**Comment by wey-gu** [comment]
closing it, thanks :-)
