### ISSUE TITLE
ping() function problem

### ISSUE THREAD

**Issue by 9606** [vesoft-inc/nebula-java#302]
I have 3 problems about this function:

1.when I get a session and call ping function，for example:
```
session = pool.getSession("root", "nebula", false);
session.ping();
```
the ping function:
```
@Override
public boolean ping() {
    try {
        client.execute(0, "YIELD 1;".getBytes());
        return true;
    } catch (TException e) {
        if (e instanceof TTransportException) {
            TTransportException te = (TTransportException) e;
            return te.getType() != TTransportException.END_OF_FILE
                    && te.getType() != TTransportException.NOT_OPEN;
        }
        return true;
    }
}
```
I modify a line:
```
@Override
public boolean ping() {
    try {
        ExecutionResponse response = client.execute(0, "YIELD 1;".getBytes());
        return true;
    } catch (TException e) {
        if (e instanceof TTransportException) {
            TTransportException te = (TTransportException) e;
            return te.getType() != TTransportException.END_OF_FILE
                    && te.getType() != TTransportException.NOT_OPEN;
        }
        return true;
    }
}
```

there is no expection, but the responce is: 
ExecutionResponse (
  error_code : E_SESSION_INVALID (E_SESSION_INVALID),
  latency_in_us : 0,
  error_msg : 49 6E 76 61 6C 69 64 20 73 65 73 73 69 6F 6E 20 69 64
)
is this response normal?

2. If the response is normal, I have added a function in branch v1.1.0, the response is the same, why the master branch say:
// Need server supported, v1.0 nebula-graph doesn't supported

3. this function in c++ client is :
```
bool Connection::ping() {
    auto resp = execute(-1 /*Only check connection*/, "YIELD 1");
    if (resp.errorCode == ErrorCode::E_RPC_FAILURE || resp.errorCode == ErrorCode::E_DISCONNECTED) {
        return false;
    }
    return true;
}
```
any sessionId <= 0 is ok? right?

**Comment by wey-gu** [comment]
@Nicole00 could you plz take a look at this?

Post in forum: https://discuss.nebula-graph.com.cn/t/topic/4199/4

**Comment by laura-ding** [comment]
Already reply on https://discuss.nebula-graph.com.cn/t/topic/4199/12, so close it.
