### ISSUE TITLE
com.vesoft.nebula.client.graph.exception.AuthFailedException: Auth failed: Authenticate failed: Expected protocol id ffffff82 but got 0

### ISSUE THREAD

**Issue by kinda830** [vesoft-inc/nebula-java#304]
com.vesoft.nebula.client.graph.exception.AuthFailedException: Auth failed: Authenticate failed: Expected protocol id ffffff82 but got 0
集群的登录验证没有开，但是登录失败

**Comment by wey-gu** [comment]
Dear @kinda830,

Could you please check one thing: the nebula java client's version matches the nebula graph server side?
- java-client version
- nebula-graph version

Thanks.

**Comment by kinda830** [comment]
nebulagraph : 2.0.0-nightly
java-client: 2.0.0

java-client：2.0.0-SNAPSHOT 这个版本的依赖无法解决，找不到这个版本

**Comment by kinda830** [comment]
> Dear @kinda830,
> 
> Could you please check one thing: the nebula java client's version matches the nebula graph server side?
> 
> * java-client version
> * nebula-graph version
> 
> Thanks.

nebulagraph : 2.0.0-nightly
java-client: 2.0.0

java-client：2.0.0-SNAPSHOT 这个版本的依赖无法解决，找不到这个版本

**Comment by wey-gu** [comment]
Dear @kinda830 

You are right, `2.0.0-SNAPSHOT` should be the client to be used as there were thrift changes between `2.0.0-nightly` and `2.0.0 GA+`, thus the RPC call including authentication itself may encounter protocol issues as you did.

@Nicole00 could you help hint @kinda830 's dependencies issue?

Thanks!

**Comment by Nicole00** [comment]
> > Dear @kinda830,
> > Could you please check one thing: the nebula java client's version matches the nebula graph server side?
> > 
> > * java-client version
> > * nebula-graph version
> > 
> > Thanks.
> 
> nebulagraph : 2.0.0-nightly
> java-client: 2.0.0
> 
> java-client：2.0.0-SNAPSHOT 这个版本的依赖无法解决，找不到这个版本

You are using Nebula nightly, please make sure the client version is 2.0.0-SNAPSHOT. You can find the snapshot version from there: https://oss.sonatype.org/content/repositories/snapshots/com/vesoft/client/2.0.0-SNAPSHOT/ 

In your own pom.xml, you can add snapshot repository to auto download `client-2.0.0-SNAPSHOT.jar`.
```
<repositories>
        <repository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>
```

**Comment by Nicole00** [comment]
> com.vesoft.nebula.client.graph.exception.AuthFailedException: Auth failed: Authenticate failed: Expected protocol id ffffff82 but got 0
> 集群的登录验证没有开，但是登录失败

Please check if you use the correct graphd's host and port, can you post your code to establish a connection with Nebula Graph ？

**Comment by aminmaghsodi** [comment]
Hi, I have the same problem.
I use client v2.0.0 and server v2.0.0
Today I see this error, every time I start my application.
Sometimes when I activate debug mode, when I execute `session.execute(some_command)`, client executes it well, but when I deactivate debug mode and run it normally it throws the below exception.

```
com.vesoft.nebula.client.graph.exception.IOErrorException: Expected protocol id ffffff82 but got 7
	at com.vesoft.nebula.client.graph.net.SyncConnection.execute(SyncConnection.java:74) ~[client-2.0.0.jar:?]
	at com.vesoft.nebula.client.graph.net.Session.execute(Session.java:46) ~[client-2.0.0.jar:?]
```

**Comment by aminmaghsodi** [comment]
Finally I found it!
In my case, the error was using one instance of `session` by multi threads.
I have designed an object pool of `session`s which keeps using sessions and assigns them to requester. In my case there was some cases that two threads request for one instance of `session` and therefore it throws the mentioned error.

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
