### ISSUE TITLE
java client api annotation not found? Can you provide?

### ISSUE THREAD

**Issue by tomatochaoegg** [vesoft-inc/nebula-java#305]

**Comment by wey-gu** [comment]
thank you @tomatochaoegg, 

we will work on that and generate API docs based on annotation in near future.
For now, you can refer to code examples to start using it(sorry for this), and if any issues encountered feel free to raise your hands here or in the forum.

Also, if you would like to contribute to this, it's also more than welcomed!

BR//Wey

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
