### ISSUE TITLE
 How to detect whether the com.vesoft.nebula.Value object is null value?

### ISSUE THREAD

**Issue by sujiulong** [vesoft-inc/nebula-java#310]
I have a property type of string and enable null value, default _EMPTY_.
When I use java client to query the value, I don’t know if the value is null. Is there any way I can know？

**Comment by Nicole00** [comment]
> I have a property type of string and enable null value, default _EMPTY_.
> When I use java client to query the value, I don’t know if the value is null. Is there any way I can know？

When you execute a gql using graph client, you can get your result value as ValueWrapper. And ValueWrapper provides method `isNull` to check if the value is null. https://github.com/vesoft-inc/nebula-java/blob/f7192b1a1978e019b77a1b1f0bdb77175867b859/client/src/main/java/com/vesoft/nebula/client/graph/data/ValueWrapper.java#L111

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
