### ISSUE TITLE
can session from pool.getSession be shared in multi-threading

### ISSUE THREAD

**Issue by wolaiye1010** [vesoft-inc/nebula-java#328]
现在每次query 的时候
pool.getSession
使用
session.release();

但发现getSession 每次都耗时3ms 耗时挺多的，想质询下，这个getSession 是否可以做成静态变量多个线程公用，而不用每次都获取使用完释放呢

**Comment by wey-gu** [comment]
Dear @wolaiye1010 

It's not allowed to be used by multiple processes, thus you can create different pools per process.
Also, don't have to release it for all cases, you can maintain it yourself if release is too costly in your use case.

You can refer to https://github.com/vesoft-inc/nebula-java/issues/322
