### ISSUE TITLE
Add fluent API to simplify the query  building 

### ISSUE THREAD

**Issue by hantsy** [vesoft-inc/nebula-java#332]
Similar to the [Neo4j Cypher API](https://github.com/neo4j-contrib/cypher-dsl),  a **Type safe** fluent API is more friendly for Java developers.

**Comment by wey-gu** [comment]
Thank you for helping inspire the community with the lovely cypher-dsl!

cc @laura-ding @Nicole00

**Comment by Nicole00** [comment]
how about the [nebula orm framework ](https://github.com/nebula-contrib/ngbatis)

**Comment by Nicole00** [comment]
no plan to support dsl for cypher.
