### ISSUE TITLE
new created tag cannot be found

### ISSUE THREAD

**Issue by hebelala** [vesoft-inc/nebula-java#340]
使用nebula-java创建TAG，然后马上使用另外的connection执行`DESC TAG`命令来查，查不到就间隔1秒后再查，但是一直查不到，是哪里有缓存？  而，一段时间后，使用其他客户端可以查到新TAG。

**Comment by wey-gu** [comment]
创建 space，tag 等修改 meta 里的数据的操作，要等两个心跳的时间才会同步的，如果程序逻辑涉及比如创建 TAG，要 sleep 一下再操作后续的依赖前边创建、修改资源的操作。

**Comment by hebelala** [comment]
明白。但是等两个心跳时间，太久了，心跳时间默认10秒的话，要等上20秒。

**Comment by Sophie-Xie** [comment]
Closed it first, if you have some new info, you can open the issue again.
