### ISSUE TITLE
Thread hangs, when storageClient scanVertex return error code

### ISSUE THREAD

**Issue by hebelala** [vesoft-inc/nebula-java#343]
Thread hangs, when storageClient scanVertex return error code.
Because the CountDownLatch is always await, while threadPool runnable occurs exception.
fix see PR https://github.com/vesoft-inc/nebula-java/pull/342 
I noticed the `ScanEdgeResultIterator` is ok.  I suggest, `ScanResultIterator` could reuse some code better.

**Comment by wey-gu** [comment]
Thank you @hebelala for the great catch and contribution :)!

**Comment by hebelala** [comment]
You are welcome~
