### ISSUE TITLE
Can nebula-java add support for spring-boot？

### ISSUE THREAD

**Issue by ZhuoSiChen** [vesoft-inc/nebula-java#345]

**Comment by wey-gu** [comment]
@Sophie-Xie

**Comment by Nicole00** [comment]
你想在Spring-Boot服务中操作Nebula吧，可以用Java Client 去操作啊，然后做一些结果转换就可以。 查询结果的转换可以参考nebula-http-gateway这个项目 https://github.com/vesoft-inc/nebula-http-gateway

**Comment by wey-gu** [comment]
如果我没理解错， @ZhuoSiChen 希望有 sprint boot 中的集成对么？这个礼拜我第二次看到这个询问（微信上不是您吧？）
您可以多说说您的需求哈。

**Comment by Anyzm** [comment]
在个人仓库已发布，过段时间上传中央仓库，开发者也可以下载源码自己改。
通过捐赠仓库的形式贡献ORM
https://github.com/Anyzm/graph-ocean

**Comment by Nicole00** [comment]
https://github.com/nebula-contrib/graph-ocean
