### ISSUE TITLE
Error code 1005

### ISSUE THREAD

**Issue by aminmaghsodi** [vesoft-inc/nebula-java#355]
I have a problem with my cluster. when I request it for fetch some items (by using `client.execut("fetch ...")`), the ResultSet has an error with error-code = `-1005` and the message is LEADER_CHANGED. and it is not going to fix during the time. How can I fix it?
And I have another question that we have LEADER_CHANGED with another code before (`-8`). What is the difference between these codes?

My nebula version is 2.5.0

**Comment by HarrisChu** [comment]
1005 means `E_EXECUTION_ERROR`

and the error code in v2.0.1 is `-8`

**Comment by Sophie-Xie** [comment]
Closed it first, if you have some new info, you can open the issue again.
