### ISSUE TITLE
Write access or create branch on nebula graph-java

### ISSUE THREAD

**Issue by aminmaghsodi** [vesoft-inc/nebula-java#362]
I want write access to one of possible new branch of nebula-java v2.5.0. could you provide access for me? There is just one choice to fork nebula-java and send merge request. Is it the unique choice?

Subject:
Prevent crashing app on init time when just one server of cluster is down. Based on what I have seen, the client application could be live on runtime when there are any graphd server. but on init time it checks for all nodes of graphd and it is in opposite to high availability.
I have resolved this problem on my local code and I want merge these new line of codes. how can I do it?

**Comment by klay-ke** [comment]
You could open a pull request and ask our team to review

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-java/pull/367
