### ISSUE TITLE
NebulaPoolConfig中timeout参数，导致新创建session失败的问题

### ISSUE THREAD

**Issue by vchangpengfei** [vesoft-inc/nebula-java#387]
在查询的应用中 新创建的session，会有两个操作1 authenticate 认证操作 2： use space操作-（第一次会比较慢，所以这里默认执行一次）
当应用启动设置了超时参数，超时参数是绑定在每个connection上的，所以上面的 1，2 会复用timeout参数
复用时 如果 meta集群负载高，或者 use space操作 时间长，会导致timeout 以至于 session 永远创建不成功

**Comment by Nicole00** [comment]
> 在查询的应用中 新创建的session，会有两个操作1 authenticate 认证操作 2： use space操作-（第一次会比较慢，所以这里默认执行一次） 当应用启动设置了超时参数，超时参数是绑定在每个connection上的，所以上面的 1，2 会复用timeout参数 复用时 如果 meta集群负载高，或者 use space操作 时间长，会导致timeout 以至于 session 永远创建不成功

你这个需求类似于Mysql 的 statement timeout， Mysql JDBC支持对每个查询语句设置不同的timeout， 但底层实现其实是把每个sql封装成了一个task，会有一个Timer来监听当前的sql查询，当超时时就会抛出异常。

你可以根据业务应用的使用，将pool中的超时时间设置为0， 然后针对不同的execute查询设置Timer 超时时间，当超出业务允许最大的执行时间时由Timer触发超时异常。

**Comment by vchangpengfei** [comment]
> 

现在的情况时，client初始化的时候 设置了超时时间，因为这个超时时间，可能导致session 认证不成功，因为认证操作比较耗时

**Comment by Nicole00** [comment]
目前我们有[jdbc](https://github.com/nebula-contrib/nebula-jdbc)，可以类似于mysql 在jdbc上做Timer的监控，监控连接和请求各自的超时时间。
