### ISSUE TITLE
Version Between Client and Nebula | Can't Run GraphClientExample.java

### ISSUE THREAD

**Issue by arstian** [vesoft-inc/nebula-java#390]
On the link https://github.com/vesoft-inc/nebula-java/ said that there are the version correspondence between client and Nebula. For nebula 2.6.1, what version of the client that can match?
And why can't I run sample java on link https://github.com/vesoft-inc/nebula-java/blob/master/examples/src/main/java/com/vesoft/nebula/examples/GraphClientExample.java ?

**Comment by wey-gu** [comment]
Sorry @andarst , please use 2.6.0 version of nebula-java.

**Comment by wey-gu** [comment]
Any errors info encountered, please?

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-java/pull/404
