### ISSUE TITLE
MetaClient addresses should support domain

### ISSUE THREAD

**Issue by hebelala** [vesoft-inc/nebula-java#394]
![image](https://user-images.githubusercontent.com/22008307/144206714-0960b0f1-47c3-4c41-ba68-280a9614f85e.png)

The Graph NebulaPool support domain address, I think MetaClient should support too.

![image](https://user-images.githubusercontent.com/22008307/144207595-a039356b-a1cd-4940-bc91-f86b0c15ecea.png)

![image](https://user-images.githubusercontent.com/22008307/144207426-aeb465f0-8992-42d8-aca8-1ceaa9d29865.png)

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-java/pull/403
