### ISSUE TITLE
Best Practices/ Examples of handling sessions

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-java#397]
We could have examples as dev docs/code examples on this.

**Comment by riverzzz** [comment]
i have multi spaces, use session how to manager multi spaces?i want to have some examples.

**Comment by neblen** [comment]
> We could have examples as dev docs/code examples on this.
When using nebula session in spark structured streaming, I use nebulaPool to get session，but it dont’t work. I want some useful example to use nebula session in spark structured streaming. Thank you very much.

**Comment by Nicole00** [comment]
> When using nebula session in spark structured streaming, I use nebulaPool to get session，but it dont’t work. I want some useful example to use nebula session in spark structured streaming. Thank you very much.

maybe you can refer  the streaming process in https://github.com/vesoft-inc/nebula-exchange

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.
