### ISSUE TITLE
server side which missing verifyClientVersion method get too many zombie connections

### ISSUE THREAD

**Issue by iiibui** [vesoft-inc/nebula-java#399]
Invalid connection didn't close immediately when ping failed cause by verifyClientVersion method missing exception(connect to nebula graph < 2.6):
https://github.com/vesoft-inc/nebula-java/blob/453064dc22161ee47a14b2e30868dc2121eb3a27/client/src/main/java/com/vesoft/nebula/client/graph/net/RoundRobinLoadBalancer.java#L75-L88

Also see:
https://github.com/vesoft-inc/nebula-java/blob/453064dc22161ee47a14b2e30868dc2121eb3a27/client/src/main/java/com/vesoft/nebula/client/graph/net/SyncConnection.java#L86-L108

client.verifyClientVersion will have no response but exception.

**Comment by Nicole00** [comment]
Great catch, thanks for raising this issue.
https://github.com/vesoft-inc/nebula-java/pull/402
