### ISSUE TITLE
get session error

### ISSUE THREAD

**Issue by funs690** [vesoft-inc/nebula-java#406]
1. nebula pool init success
2. for long time not to use the connection
3.  then to get the connetion will cost long time to get the session

  minConnsSize: 3
  maxConnsSize: 10

**Comment by funs690** [comment]
Version 2.6.1

**Comment by vchangpengfei** [comment]
This should be not enough connections available, if you want to return, the waitTime parameter you can set NebulaPoolConfig

**Comment by funs690** [comment]
set the "minConnsSize:3" means the pool will keep least 3 connections or need keepalive ?

**Comment by Nicole00** [comment]
> set the "minConnsSize:3" means the pool will keep least 3 connections or need keepalive ?

yeah,  the pool will evict connections when the size of idle connections larger than minConnsSize. But it allows the size of connection less than minConnsSize.  And please notice that, when init pool, it will not create minConnsSize connections for you , only when you need  it creates connection object.
refer to https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/GenericObjectPoolConfig.html#setMinIdle-int-
