### ISSUE TITLE
统计某个space中所有leader的分布错误

### ISSUE THREAD

**Issue by luoyeguigen001** [vesoft-inc/nebula-java#408]
在一个3节点的集群上，通过getSpaceParts获取某个space的parts后，遍历每一个parts，获取其leader
获得的leader显示的结果与通过console显示的不一样
应该是通过client获取的数据有问题，3个storage我停止了一个后，console显示节点上的leader是0，61,  67, 而测试代码一致是42,43,43

**Comment by Nicole00** [comment]
> 

请问你是通过metaManager来调用getSpaceParts 获取space所有的part信息的么，可以贴一下你的测试代码吗

**Comment by luoyeguigen001** [comment]
java的调用是metaManager.getSpaceParts("test"); python的调用是meta_cache.get_part_leader("test")，使用python和java的client调用的都是显示42。43。43。

**Comment by Nicole00** [comment]
client调用的都是cache里面的数据，你拿到的是meta cache初始化时刻的part信息，当服务更新后cache不会及时被更新的，只有当查到某个cache中不存在的space、tag或者edge时，cache会被更新。

**Comment by Sophie-Xie** [comment]
Closed it first, if you have some new info, you can open the issue again.
