### ISSUE TITLE
建议去掉fastjson依赖，使用jackson

### ISSUE THREAD

**Issue by melin** [vesoft-inc/nebula-java#421]
现在很多公司不推荐使用fastjson，使用jackson，依赖导入项目，容易被项目开发员使用。

**Comment by wey-gu** [comment]
Thanks, @melin!
@Nicole00 what do you think, please?

**Comment by Nicole00** [comment]
> 

Thanks for offering this idea, we found that `Fastjson` does have some usage issues, and its fastness may lead to memory issues. We will consider replacing fastjson with jackson, thanks again.

**Comment by Nicole00** [comment]
> 现在很多公司不推荐使用fastjson，使用jackson，依赖导入项目，容易被项目开发员使用。

In nebula-java， fastjson is used just in test, we can just set fastjson's dependency as provided or test, then it will not be packaged into jar.
