### ISSUE TITLE
使用nebula-jdbc或nebula-java获取session的问题

### ISSUE THREAD

**Issue by mathlpz** [vesoft-inc/nebula-java#441]
使用nebula-jdbc或nebula-java获取session的问题：
nebula 版本：2.5.1
nebula-java版本 ：2.5.0
部署方式：分布式
安装方式：RPM
是否为线上版本： N
硬件信息
磁盘：200G SSD
CPU、内存信息：8核16G
问题的具体描述：
目前基于java语言使用nebula-jdbc开发后端服务系统，遇到了如下几个问题：
1、在nebula-java客户端代码中，java代码获取nsid（即sessionId），只能通过SyncConnection吗？NebulaDriver和Connection都获取不到sessionId。获取sessionId的示例：
SyncConnection connection = new SyncConnection();
connection.open(new HostAddress(“127.0.0.1”,“9669”), 1000);
AuthResult authResult = connection.authenticate(req.getUsername(), req.getPassword());
String nsid = String.valueOf(authResult.getSessionId());

2、做java服务端开发，首次获取到nsid（sessionId）后，需要自己保存维护吧？后续调用其它接口（如gql查询execute接口）需要带上nsid查询，避免每次都重新获取数据库连接。但是目前看client源码，只有SyncConnection的执行方法有通过sessionID查询的方案，其它像Connection查询方法没有通过sessionID查询方法，都是每次要重新获取数据库连接。

3、是否有java语言使用nebula-jdbc（或nebula-java）开发的系统平台demo，可供参考学习？

**Comment by mathlpz** [comment]
java代码获取session问题，可参见discuss问答内容：
https://discuss.nebula-graph.com.cn/t/topic/7533/7
可直接用NebulaPool中getSession获取session后，在服务中维护使用。但是，目前Java客户端的Session不支持序列化，所以在分布式系统中存在无法序列化的问题。
临时的解决方案是：在每个worker节点上单独初始化连接池，获取Session维护使用（如果work节点停掉，session即消失）。
问题点：希望后续版本能尽快支持session序列化功能。

**Comment by Minnull** [comment]
等一个

**Comment by wey-gu** [comment]
等到了！nebula-java 3.3.0 引入了 session pool，现在可以愉快地使用 session pool 了哈！

https://github.com/vesoft-inc/nebula-java/blob/f4431aa71a15230c7eb9e7299ab47efad2b0c27e/examples/src/main/java/com/vesoft/nebula/examples/GraphClientExample.java#L100

**Comment by wey-gu** [comment]
@mathlpz @Minnull

**Comment by Minnull** [comment]
> 等到了！nebula-java 3.3.0 引入了 session pool，现在可以愉快地使用 session pool 了哈！
> 
> https://github.com/vesoft-inc/nebula-java/blob/f4431aa71a15230c7eb9e7299ab47efad2b0c27e/examples/src/main/java/com/vesoft/nebula/examples/GraphClientExample.java#L100

我看这个还无法直接在业务逻辑中使用，因为每次获取session还都会new session，所以需要自己在外面维护一个session列表重复利用吗？
然后我看有个link，session池参考这个写：https://github.com/vesoft-inc/nebula-java/pull/476/commits/ec375626ff3bd706c55906a4a7b1129c87305bbe

这样理解对吗？

**Comment by wey-gu** [comment]
> 

没错，这是 session pool，不是 connection pool
