### ISSUE TITLE
什么时候能有Java的ORM框架？

### ISSUE THREAD

**Issue by z921887787** [vesoft-inc/nebula-java#452]
需求如标题，现在使用Java client还是有很多不方便。

**Comment by wey-gu** [comment]
check this out https://github.com/nebula-contrib/graph-ocean :)

**Comment by CorvusYe** [comment]
If your project is base on springboot , you can try [ngbatic](https://github.com/CorvusYe/ngbatis) out. 
But this project is developing. 
Give me some advice please @z921887787

**Comment by wey-gu** [comment]
We have 2 NebulaGraph Java ORM now as above!
