### ISSUE TITLE
Add filter for scanVertex and scanEdge

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-java#455]
There is such interface on thrift and server-side, this could enable spark-connector to scan data with filter, which is a feature requested by users for some time :-D

**Comment by vchangpengfei** [comment]
Does server 2.6.1 support this feature? I see that the filter in ScanVertexRequest class needs StorageClient support, right?

**Comment by Nicole00** [comment]
depends on NebulaGraph Storaged server's implementation.
