### ISSUE TITLE
May I request a feature about Session status.

### ISSUE THREAD

**Issue by CorvusYe** [vesoft-inc/nebula-java#462]
Maybe we need a status in Session. 
For example:
- NEW
- RUNNABLE
- RUNNING
- BROKEN

> When the execution is completed and not released, it should be RUNNABLE status.

This feature can help developers use session multiple times and skip authentication. And different front end user can use different DB  session in the same time not limited by synchronized.

**Comment by Nicole00** [comment]
The session status is transparent for users, and users need not to concern the session status. When a session is not released, you can use it continue without auth. And when you get a session from NebulaPool, it must be a new session, you can use it to execute statement too.
