### ISSUE TITLE
Java Client 3.0.0 has 3 CVE from its dependencies

### ISSUE THREAD

**Issue by GoGoMonkey123** [vesoft-inc/nebula-java#463]
![image](https://user-images.githubusercontent.com/30927013/179876181-42167592-8832-4ab7-b881-76361a94e6d9.png)

Maybe replace with other dependencies?

**Comment by wdroste** [comment]
I believe this is fixed in this PR.
https://github.com/vesoft-inc/nebula-java/pull/486

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
