### ISSUE TITLE
Java Client 3.0.0 返回数据没有 byte、short、int、float类型

### ISSUE THREAD

**Issue by azydon** [vesoft-inc/nebula-java#464]
Java Client 3.0.0 返回数据没有 byte、short、int、float类型

**Comment by Nicole00** [comment]
> Java Client 3.0.0 返回数据没有 byte、short、int、float类型

Client 里面将byte、short、int统一返回成了long
float, double 统一返回成了double

**Comment by QingZ11** [comment]
这个 issue 近一个月没有更新的内容，这边先行关闭了哈。如果你有新的更新内容，记得再打开 issue 哈~ 谢谢 azydon 的反馈
