### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.thrift.transport.TSocket

### ISSUE THREAD

**Issue by xhrwp** [vesoft-inc/nebula-java#465]
目前测试 client-verion : 2.6.0,  3.0.0

**Comment by Nicole00** [comment]
maybe there's some version conflict for thrift in your project.

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.
