### ISSUE TITLE
cast value with asXxx

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-java#466]
ref https://github.com/vesoft-inc/nebula-python/pull/222

This will be handy for users to get the wrapped value with one go.

**Comment by Nicole00** [comment]
No need to wrap a cast function in Java. 
If we provide this function:
```
    public Object cast(ValueWrapper valueWrapper){
        if(valueWrapper.isNull()){
            return null;
        }else if(valueWrapper.isString()){
            return valueWrapper.asString();
        }else if(valueWrapper.isLong()){
            return valueWrapper.asLong();
        }else if{}
        ...
    }
```
Then user get an `Object`, and when they need to get the object's datatype, they still need to judge the Object's class type.
So they can just write the cast function to get the Value's specific class type.

**Comment by wey-gu** [comment]
ok :)
