### ISSUE TITLE
3.0.0版本可以适配3.2.0的nebula吗？

### ISSUE THREAD

**Issue by rxtm** [vesoft-inc/nebula-java#471]
maven仓库里没有3.0-SNAPSHORT版本，最新的就是3.0.0

**Comment by wey-gu** [comment]
> maven仓库里没有3.0-SNAPSHORT版本，最新的就是3.0.0

可以的哈！

**Comment by Nicole00** [comment]
> maven仓库里没有3.0-SNAPSHORT版本，最新的就是3.0.0

1. 3.0.0的client 可以适配3.2.0的nebula
2. 3.0-SNAPSHOT版本在maven的snapshot仓库 https://oss.sonatype.org/content/repositories/snapshots/com/vesoft/client/
