### ISSUE TITLE
client to handle the case when session expired due to long idle

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-java#475]
The client itself could help handle this exception without needing the application layer to take care of it, which is a common pattern to implement.

This could be part of the session pool implementation.

**Comment by wey-gu** [comment]
cc @MuYiYong

**Comment by MuYiYong** [comment]
I suggest fixing it in v3.4.0. @Sophie-Xie

**Comment by wey-gu** [comment]
> I suggest fixing it in v3.4.0. @Sophie-Xie The idle time should be allowed to be configured. But what is the recommended default time? 24 hours @wey-gu

As talked offline, if feasible, we could make nebula-java to identify this particular exception and handle it transparently to the application layer/ dev user.

**Comment by Nicole00** [comment]
I think this problem does not exist in the current version. There is a scheduled task for health check in `SessionPool`. During the health check, the session will send a simple request to the server, and determine whether the current session is available according to the server's response. And The period of the health check can be configured by the user, see [code](https://github.com/vesoft-inc/nebula-java/blob/b633414754c2c80bda72d2804c77ecd1a7cf632c/client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java#L36), default period is 600s. As long as the period is less than the session idle time of the server, it can ensure that the session will not expire.
@wey-gu @Sophie-Xie @MuYiYong

**Comment by wey-gu** [comment]
> I think this problem does not exist in the current version. There is a scheduled task for health check in `SessionPool`. During the health check, the session will send a simple request to the server, and determine whether the current session is available according to the server's response. And The period of the health check can be configured by the user, see [code](https://github.com/vesoft-inc/nebula-java/blob/b633414754c2c80bda72d2804c77ecd1a7cf632c/client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java#L36), default period is 600s. As long as the period is less than the session idle time of the server, it can ensure that the session will not expire. @wey-gu @Sophie-Xie @MuYiYong

Yes, I noted your session pool implementation days ago to realize that you had defined session pool client-side idle mechanism and suggested to be configure less than the server side expiration timer(nice 👍🏻), thus to solve this issue already! Thanks!!!
