### ISSUE TITLE
UnsupportedEncodingException is a checked exception making lamdas awkward.

### ISSUE THREAD

**Issue by wdroste** [vesoft-inc/nebula-java#494]
**Introduction**
Part of making an API easy to use in Java is knowning when to use RuntimeException vs a checked exception. In all the places where a string is decoded there's a checked exception UnsupportedEncodingException.  Which in turn creates fricition and code like this for lamda functions. Basically the exception must be handled inside the lamdba which means converting it to a runtime exception.

```
      .flatMap(
          label -> {
            try {
              return n.properties(label).entrySet().stream();
            } catch (UnsupportedEncodingException e) {
              throw new IllegalArgumentException(e);
            }
          })
```

The ask here would be to make `UnsupportedEncodingException` a runtime exception.

**Comment by wey-gu** [comment]
@Nicole00

**Comment by Nicole00** [comment]
good issue!
in fact, the UnsupportedEncodingException is a place holder to support more encoding. I have recorded it for next major version. Thanks for your reminder and feedback.

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
