### ISSUE TITLE
com.vesoft.nebula.client.graph.SessionPool#useSpaceForJson

### ISSUE THREAD

**Issue by Minnull** [vesoft-inc/nebula-java#497]
请问，这个方法com.vesoft.nebula.client.graph.SessionPool#useSpaceForJson怎么没有被其他地方调用

**Comment by Nicole00** [comment]
> 

useSpaceForJson is a private function and is place holder for `executeJson`.

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
