### ISSUE TITLE
使用SessionPool时出现Socketexception

### ISSUE THREAD

**Issue by hL-ab** [vesoft-inc/nebula-java#506]
现象：
com.vesoft.nebula.client.graph.SessionPool#execute中的代码
`resultSet = nebulaSession.execute(stmt);`
抛出异常`Socketexception：断开的管道`。推测是因为超时（这并不重要）。

建议：
是否应当捕获该异常，从而能够重连连接？

**Comment by Nicole00** [comment]
3.4.1 已支持重连，且[pr](https://github.com/vesoft-inc/nebula-java/pull/522) 能支持更大强度的重连，重连次数和间隔时长允许可配置
