### ISSUE TITLE
Whether the session can be released when the resultSet is null

### ISSUE THREAD

**Issue by soul-gin** [vesoft-inc/nebula-java#509]
When resultSet is null, there may be a network problem. If the corresponding session is not released, subsequent queries will be affected.
`private boolean isSessionError(ResultSet resultSet) {
        return resultSet != null
                && (resultSet.getErrorCode() == ErrorCode.E_SESSION_INVALID.getValue()
                || resultSet.getErrorCode() == ErrorCode.E_SESSION_NOT_FOUND.getValue()
                || resultSet.getErrorCode() == ErrorCode.E_SESSION_TIMEOUT.getValue());
}
`

**Comment by Nicole00** [comment]
> When resultSet is null, there may be a network problem. If the corresponding session is not released, subsequent queries will be affected.

thanks for proposing this issue, could you please post the exception stack when your resultSet is null

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
