### ISSUE TITLE
Nebula CaSignedSSLParam support encryption for the client private key

### ISSUE THREAD

**Issue by joeyongjian** [vesoft-inc/nebula-java#510]
I think there is a security requirement that client private key can be encrypted if I use the SSL authentication to connect Nebula by nebula-java.

Now I just can define the path for the certs like crtFilePath, keyFilePath, caCrtFilePath. But somehow I need to encrypt the cert file. However the CASignedSSLParam doesn't contain the parameter "password".

I suggest this parameter should be added in CASignedSSLParam and I can pass it in nebula-java.

**Comment by Nicole00** [comment]
> for the certs like crtFilePath, keyFile

self signed ssl parameter contains the `password`. If you use ca signed, you want to encrypt the cert file using password inside the client?

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
