### ISSUE TITLE
 The performance of using java api to query nebula is weaker than that of nebula console

### ISSUE THREAD

**Issue by neojoe** [vesoft-inc/nebula-java#514]
I installed nebulagraph on the server with docker
Server configuration: cpu 16v, memory 128g, 150G ESSD cloud disk
Execute the same query logic
nebula console: MATCH p = allShortestPaths((a:point{name:"13644:5"})-[e*..7]-(b:point{name:"5119:1"})) RETURN p;
The query time is about 700ms
![image](https://user-images.githubusercontent.com/20881163/222141435-15e85ff8-a7b1-4d11-9b92-9d224414d5d3.png)

While using the nebula java api to execute the same logic, it takes 65s
![image](https://user-images.githubusercontent.com/20881163/222142594-0a7d970d-8dbf-401f-b53f-9582e2246c41.png)

May I ask what is the reason

**Comment by Nicole00** [comment]
你对比下两种语言的latency， latency是服务端的执行时间
你上面提到的700ms是latency， 65s是java client的请求响应时间。 console中的请求响应时间是4m17.xxxs

**Comment by QingZ11** [comment]
@neojoe 这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
