### ISSUE TITLE
Can the corresponding session be released after the Nebula service restarts abnormally?

### ISSUE THREAD

**Issue by soul-gin** [vesoft-inc/nebula-java#529]
**Introduction**
1. Obtain the session from the session pool and query normally
2. nebula.service restart graphd
3. If the corresponding session query is not released, it will continue to fail

**Contents**

![1689218637768](https://github.com/vesoft-inc/nebula-java/assets/34204781/f9a2414a-44a9-44e5-aeda-bda49fd89f83)

![image](https://github.com/vesoft-inc/nebula-java/assets/34204781/95828021-d29a-43ee-9982-08884b0e6d95)

**Comment by Nicole00** [comment]
After nebula.graphd server restarted, the session's connection will be unavailable, so the session can not be released by client, only wait to to released until it expires in nebula.metad.

For SessionPool, we do not to migrate the session between different graphd servers.
