### ISSUE TITLE
long time used when next()

### ISSUE THREAD

**Issue by ysjiao** [vesoft-inc/nebula-java#535]
The program is stuck when use next() of ScanVertexResultIterator

**Comment by Nicole00** [comment]
> The program is stuck when use next() of ScanVertexResultIterator

do you have any log for storaged info?

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。
