### ISSUE TITLE
 Idle session clean is inaccurate

### ISSUE THREAD

**Issue by awang12345** [vesoft-inc/nebula-java#536]
nebula-java 
**version:** 3.6.0
**class :** com.vesoft.nebula.client.graph.SessionPool

**code:**

> /**
>      * update the session queue according to minSessionSize
>      */
>     private void updateSessionQueue() {
>         // remove the idle sessions
>         if (idleSessionSize.get() > minSessionSize) {
>             synchronized (this) {
>                 for (NebulaSession nebulaSession : sessionList) {
>                     if (nebulaSession.isIdle()) {
>                         nebulaSession.release();
>                         sessionList.remove(nebulaSession);
>                         if (idleSessionSize.decrementAndGet() <= minSessionSize) {
>                             break;
>                         }
>                     }
>                 }
>             }
>         }
>     }

**desc**
This code logic simply clears the idle session.However, the idle time is not judged.It may be cleared as soon as it enters idle.
Although the scheduled tasks are scheduled according to cleanTime.But it still doesn't match the comments of

 'cleanTime' propties.

>  // The idleTime for clean the idle session
>  // must be less than NebulaGraph's session_idle_timeout_secs, unit: second
>  private int cleanTime = 3600;

**Comment by Nicole00** [comment]
Sorry for the misunderstanding caused by the configuration item, the `cleanTime` means  how often the client will clean up the idle session, not to clear the session that has been idle for this time.

**Comment by awang12345** [comment]
I know cleanTime is the frequency of cleantime,I know cleanTime is the frequency of cleantime,eg:T1、T2、T3 is the timeline of clientTime task schdule.R is the session return to pool. R just release could be recycled.
`
Timeline:-------------------T1--------------------------------T2-------------------------------T3----------------------
Timeline:----------- --R1---------------------------------R2--------------------------------R3--------------------------
`

**Comment by Nicole00** [comment]
Yeah,  R is just released and the clean schedule task is triggered, the session R may be recycled if the idle is larger than minSessionSize and R's location is in the front of SessionPool list. 
Every Session used to make execution is get from session pool, the recycle will not confluence the execution.

**Comment by awang12345** [comment]
thank you for the response
