### ISSUE TITLE
Support scala with zio

### ISSUE THREAD

**Issue by jxnu-liguobin** [vesoft-inc/nebula-java#540]
[ZIO](https://github.com/zio/zio) is  a type-safe, composable library for async and concurrent programming in Scala.

This would allow nebula-java to be used directly in an asynchronous, composable way, for example:
```scala
object NebulaSessionPoolExampleMain extends ZIOAppDefault {

  override def run = (for {
    _ <- ZIO.serviceWithZIO[NebulaSessionPoolService](
             _.execute("""
                         |INSERT VERTEX person(name, age) VALUES 
                         |'Bob':('Bob', 10), 
                         |'Lily':('Lily', 9),'Tom':('Tom', 10),
                         |'Jerry':('Jerry', 13),
                         |'John':('John', 11);""".stripMargin).flatMap(r => ZIO.logInfo(r.toString))
           )
    _ <- ZIO.serviceWithZIO[NebulaSessionPoolService](
             _.execute("""
                         |INSERT EDGE like(likeness) VALUES
                         |'Bob'->'Lily':(80.0),
                         |'Bob'->'Tom':(70.0),
                         |'Lily'->'Jerry':(84.0),
                         |'Tom'->'Jerry':(68.3),
                         |'Bob'->'John':(97.2);""".stripMargin).flatMap(r => ZIO.logInfo(r.toString))
           )
    _ <- ZIO.serviceWithZIO[NebulaSessionPoolService](
             _.execute("""
                         |USE test;
                         |MATCH (p:person) RETURN p LIMIT 4;
                         |""".stripMargin)
               .flatMap(r => ZIO.logInfo(r.getRows.toString()))
           )
  } yield ())
    .provide(
      Scope.default,
      NebulaSessionPool.layer,
      NebulaConfig.layer,
      NebulaSessionPoolService.layer
    )
}
```
Anyone can build their own nebula service using just `NebulaSessionPool.layer` and `NebulaConfig.layer`.
Using [typesafe config](https://github.com/lightbend/config) and HOCON makes it easier to get the configuration from the configuration center.

I have completed the initial implementation, is it possible to move it to nebula-contrib? I will continue to maintain it in the meantime.

**Comment by Nicole00** [comment]
> [ZIO](https://github.com/zio/zio) is a type-safe, composable library for async and concurrent programming in Scala.
> 
> This would allow nebula-java to be used directly in an asynchronous, composable way, for example:
> 
> ```scala
> object NebulaSessionPoolExampleMain extends ZIOAppDefault {
> 
>   override def run = (for {
>     _ <- ZIO.serviceWithZIO[NebulaSessionPoolService](
>              _.execute("""
>                          |INSERT VERTEX person(name, age) VALUES 
>                          |'Bob':('Bob', 10), 
>                          |'Lily':('Lily', 9),'Tom':('Tom', 10),
>                          |'Jerry':('Jerry', 13),
>                          |'John':('John', 11);""".stripMargin).flatMap(r => ZIO.logInfo(r.toString))
>            )
>     _ <- ZIO.serviceWithZIO[NebulaSessionPoolService](
>              _.execute("""
>                          |INSERT EDGE like(likeness) VALUES
>                          |'Bob'->'Lily':(80.0),
>                          |'Bob'->'Tom':(70.0),
>                          |'Lily'->'Jerry':(84.0),
>                          |'Tom'->'Jerry':(68.3),
>                          |'Bob'->'John':(97.2);""".stripMargin).flatMap(r => ZIO.logInfo(r.toString))
>            )
>     _ <- ZIO.serviceWithZIO[NebulaSessionPoolService](
>              _.execute("""
>                          |USE test;
>                          |MATCH (p:person) RETURN p LIMIT 4;
>                          |""".stripMargin)
>                .flatMap(r => ZIO.logInfo(r.getRows.toString()))
>            )
>   } yield ())
>     .provide(
>       Scope.default,
>       NebulaSessionPool.layer,
>       NebulaConfig.layer,
>       NebulaSessionPoolService.layer
>     )
> }
> ```
> 
> Anyone can build their own nebula service using just `NebulaSessionPool.layer` and `NebulaConfig.layer`. Using [typesafe config](https://github.com/lightbend/config) and HOCON makes it easier to get the configuration from the configuration center.
> 
> I have completed the initial implementation, is it possible to move it to nebula-contrib? I will continue to maintain it in the meantime.

WAW!!! A very novel way to build a nebula service. Of course you can migrate your implementation to nebula-contrib, looking forward to your contribution~ thanks very much.

**Comment by jxnu-liguobin** [comment]
Hey @Nicole00 my repository is here https://github.com/hjfruit/zio-nebula,  i'm ready to transfer zio-nebula to nebula-contribat at any time

**Comment by wey-gu** [comment]
This is amazing @jxnu-liguobin ! It's so very lucky to have you(another scala hacker!) in the community :-D.

I loved that logo!!!

cc @QingZ11 could you please help with @jxnu-liguobin 's donation journey?

**Comment by Nicole00** [comment]
the implementation for scala is [here](https://github.com/nebula-contrib/zio-nebula) , now close the issue. Thanks @jxnu-liguobin for your contribution~
