### ISSUE TITLE
SessionPool 连接 3 节点集群时，一个节点宕机后，客户端无法连接，请问怎么设置集群可用度?

### ISSUE THREAD

**Issue by momoco530** [vesoft-inc/nebula-java#549]
**General Question**
如标题所示

**Comment by Nicole00** [comment]
sessionpool是在某些graphd服务宕机后允许进行连接重试的，你要看下你的代码中是否有配置reconnect为true。

**Comment by momoco530** [comment]
> sessionpool是在某些graphd服务宕机后允许进行连接重试的，你忽略下你的代码中是否有配置reconnect为true。

十分感谢

**Comment by momoco530** [comment]
完成

**Comment by momoco530** [comment]
已经修改
