### ISSUE TITLE
typo in examples?

### ISSUE THREAD

**Issue by jxnu-liguobin** [vesoft-inc/nebula-java#550]
https://github.com/vesoft-inc/nebula-java/blob/12452cb7b92f514b9f18fb2a715c97c701f097b5/examples/src/main/java/com/vesoft/nebula/examples/GraphSessionPoolWithHttp2Example.java#L33

https://github.com/vesoft-inc/nebula-java/blob/12452cb7b92f514b9f18fb2a715c97c701f097b5/examples/src/main/java/com/vesoft/nebula/examples/GraphSessionPoolExample.java#L28

**Comment by wey-gu** [comment]
Looks like so, would you mind PR to correct the class names accordingly?
