### ISSUE TITLE
The effective time of space is not friendly to testing

### ISSUE THREAD

**Issue by jxnu-liguobin** [vesoft-inc/nebula-java#552]
**Is your feature request related to a problem? Please describe.**

I am testing the Nebula application by testcontainers. Of course, testcontainers do not support nebula now,  I have written a simple tool [testcontainers-nebula](https://github.com/hjfruit/testcontainers-nebula).

The document suggests that creating a space requires a wait of 20 seconds before it becomes available, which is good for distributed systems, but it is cumbersome for testing, which means that you must **retry** or **manually sleep**. The latter is not easily achieved correctly in asynchronous programs, and the number of retries for the former is unknown. 

For this issue, in zio, I had to use the eventually aspect to make my testing ultimately successful (Try again until successful), obviously, this is time-consuming and unknown, and **may never succeed**. 

`heartbeat_interval_secs` It seems that the configuration controls this, but can it take effect immediately?

**Describe the solution you'd like**
For this, allowing clients to register callbacks to inform users in a timely manner or effective immediately?.

**Describe alternatives you've considered**

**Additional context**

**Comment by Nicole00** [comment]
>heartbeat_interval_secs It seems that the configuration controls this, but can it take effect immediately?

The configuration is static, must restart graphd server to make it take effect.

@jxnu-liguobin  Thanks for your test tool, It will  be a friendly and effective tool for users to make nebula related test. Could you please contribute your great test container to [esoft-contrib? ](https://github.com/nebula-contrib) cc  @QingZ11 @wey-gu

**Comment by wey-gu** [comment]
Wow, second project in a role!!!!🚀
