### ISSUE TITLE
Does NebulaGraph support image storage?

### ISSUE THREAD

**Issue by momoco530** [vesoft-inc/nebula-java#557]
**General Question**

**Comment by Nicole00** [comment]
一般存储图片两种方式，
1.直接存储：把图片直接以二进制形式存储在数据库中。
2.间接存储：图片存储在磁盘上（服务器上），数据库字段中保存的是图片在服务器上存储的路径。

**Comment by momoco530** [comment]
采用了 Base64 将二进制转换为 String 进行了存储
