### ISSUE TITLE
客户端连接集群问题

### ISSUE THREAD

**Issue by momoco530** [vesoft-inc/nebula-java#559]
你好，目前我配置了三台服务器 10.21.1.10、10.21.1.11、10.21.1.12

nebula-graphd.conf
> --meta_server_addrs=10.21.1.10:9559,10.21.1.11:9559,10.21.1.12:9559

nebula-metad.conf
> --meta_server_addrs=10.21.1.10:9559,10.21.1.11:9559,10.21.1.12:9559

ebula-storaged.conf
> --meta_server_addrs=10.21.1.10:9559,10.21.1.11:9559,10.21.1.12:9559

客户端配置如下

> SessionPoolConfig sessionPoolConfig = new SessionPoolConfig(addresses, space, userName, password);
> sessionPoolConfig.setMinSessionSize(minSessionSize);
> sessionPoolConfig.setMaxSessionSize(maxSessionSize);
> sessionPoolConfig.setTimeout(sessionTimeout);
> sessionPoolConfig.setCleanTime(clearTime);
> sessionPoolConfig.setIntervalTime(intervalIdel);
> sessionPoolConfig.setWaitTime(waitTime);
> sessionPoolConfig.setHealthCheckTime(healthCheckTime);
> sessionPoolConfig.setReconnect(reconnect);

当其中任一节点宕机或停止服务时，客户端无法连接到集群，
或发生 -1005:GraphMemoryExceeded:(-2600) 异常时，客户端连接报错信息如下
> [ERROR (-1005)]: Storage Error: RPC failure, probably timeout.

请问这个问题是存在什么配置或我的集群安装问题吗?

**Comment by Nicole00** [comment]
报错信息显示是Storaged挂了，你的查询错报了，并不是连接不上集群。 在SessionPool初始化之后，如果还有graphd是活着的，你还是可以正常连接上nebula服务的。

**Comment by momoco530** [comment]
你好，如果三台服务器的 Storaged 挂了一个，就无法进行查询了吗?
还是说有什么配置需要调整的？

**Comment by QingZ11** [comment]
> 我目前的情况就是三个 Storaged 挂了一个，客户端就无法连接了，抛出的就是”Storage Error: RPC failure, probably timeout.“ 还是说有什么配置需要调整吗？ ![image](https://user-images.githubusercontent.com/13846903/279058065-7cda1cee-c0c6-4cba-a11c-3ba33c6cddcd.png)

挂掉的那个 storage 可以重启下么？show hosts graph 你看下是不是有 graph 挂了，而你这个客户端是不是连上了挂掉的 graph。（是的话，可以尝试换下 graph 的配置顺序

**Comment by QingZ11** [comment]
这个问题有段时间了，如果你有新的信息更新的话，可以重新打开这个 issue 哈。
