### ISSUE TITLE
When will storageclient provide the 'socketTimeout' parameter?

### ISSUE THREAD

**Issue by awang12345** [vesoft-inc/nebula-java#562]
nebula-client 
version:3.6
desc:
At present, socketTimeout defaults to 1 second, which is easy to timeout when the amount of scan data is large or the network is slow and the storage service responds slowly

**Comment by Nicole00** [comment]
> nebula-client version:3.6 desc: At present, socketTimeout defaults to 1 second, which is easy to timeout when the amount of scan data is large or the network is slow and the storage service responds slowly

There is interfaces to config the timeout for StorageClient.
https://github.com/vesoft-inc/nebula-java/blob/86d4a76c9fd8697e28b79fa3704406306dc7160c/client/src/main/java/com/vesoft/nebula/client/storage/StorageClient.java#L73
