### ISSUE TITLE
nebula-java session会话

### ISSUE THREAD

**Issue by 8280-max** [vesoft-inc/nebula-java#581]
**General Question**

nebula-java 每次执行图数据库语句是否需要创建新的session会话，或者是一直用同一个会话

**Comment by Nicole00** [comment]
> **General Question**
> 
> nebula-java 每次执行图数据库语句是否需要创建新的session会话，或者是一直用同一个会话

可以一直用同一个session的，而且建议用同一个session，减少重建session带来的开销

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。
