### ISSUE TITLE
guava version is too low and not safety

### ISSUE THREAD

**Issue by VoisLp** [vesoft-inc/nebula-java#62]
guava version is too low and not safety

guava 14.0 getHostText not used in guava which version > 20

**Comment by gcameo** [comment]
I also tried to fix this but realised there is a pull request pending... so cancelled mine. Any thoughts when this will be merged?

**Comment by darionyaphet** [comment]
Incompatible with Spark Writer.

**Comment by everywan** [comment]
I submitted a PR to fix it.

I need use exchange, it depends on client-1.0.
