### ISSUE TITLE
AsyncGraphClient switchspace 空指针

### ISSUE THREAD

**Issue by firepation** [vesoft-inc/nebula-java#79]
代码库中提供的 AsyncGraphClientExample 例子，执行到 switchspace 时报空指针异常，debug 后发现是 ListeningExecutorService service 对象为空，该对象通过 AsyncAbstractClient 的 connect 方法初始化，但是 AsyncGraphClientImpl 覆写了 connect 方法，导致 service 对象没有初始化，这个是代码中的 bug 吗？

**Comment by darionyaphet** [comment]
FIX: #50 Please update your source code and retry thanks :)
