### ISSUE TITLE
ngql查询bug

### ISSUE THREAD

**Issue by Anyzm** [vesoft-inc/nebula-java#81]
1、go FROM uuid("b3d8ff87f7e9690bbf33f7afad368a8c")  OVER call BIDIRECT where call._dst==uuid("b3d8ff87f7e96978979879878787")
想要查询两个顶点是否在同一条边，如此查询报错，因为条件值后面不能接uuid。

2、go FROM uuid("b3d8ff87f7e9690bbf33f7afad368a8c") OVER use_wifi,use_device YIELD use_wifi._dst as use_wifi_id,use_device._dst as use_device_id | go FROM $-.use_wifi_id,$-.use_device_id OVER use_wifi,use_device REVERSELY
想要查询出边与uuid("b3d8ff87f7e9690bbf33f7afad368a8c") 的出边为共同顶点的顶点，且是多个类型的边，在管道中id列表使用多个变量时报错。

希望查询条件后面可以接uuid，希望id列表可以使用多个变量

**Comment by darionyaphet** [comment]
This not the java client's bug. You can republish to nebula's issues.
