### ISSUE TITLE
Support reconnection

### ISSUE THREAD

**Issue by darionyaphet** [vesoft-inc/nebula-java#88]
When the session exceeds the idle time, we should reconnection it.

**Comment by rxtm** [comment]
where is the PooledGraphClient? I can not find it in master branches

**Comment by wey-gu** [comment]
> where is the PooledGraphClient? I can not find it in master branches

Please refer to https://github.com/vesoft-inc/nebula-java/blob/master/examples/src/main/java/com/vesoft/nebula/examples/GraphClientExample.java

**Comment by wey-gu** [comment]
@darionyaphet @laura-ding is it ready to close this issue(it's supported already I suppose)? and how about some housekeeping for other issues in this repo?

**Comment by laura-ding** [comment]
> @darionyaphet @laura-ding is it ready to close this issue(it's supported already I suppose)? and how about some housekeeping for other issues in this repo?

This is talking about 1.0  java client.

**Comment by klay-ke** [comment]
closed since it is added in v2.0
