### ISSUE TITLE
Strorage-Client get list key report an error

### ISSUE THREAD

**Issue by zmh0531** [vesoft-inc/nebula-java#92]
Java Client 在使用 public Optional<Map<String, String>> get(String space, List<String> keys); 这个接口的时候报错
![image](https://user-images.githubusercontent.com/31470427/83530391-3f6e0c00-a51e-11ea-9c70-47474485cb0c.png)

**Comment by jerroldgao** [comment]
是不是Optional制定的时候没有制定默认值，NullPointerException是个trivial的问题。能不能更详细一点描述错误。

**Comment by zmh0531** [comment]
https://github.com/vesoft-inc/nebula-java/blob/63403bce3d42cf836e2b6ca8971fd80364014a06/client/src/main/java/com/vesoft/nebula/client/storage/StorageClientImpl.java#L305

应该是线程池没有初始化，现在改好了。

还有这个计数器初始化数值是不是错了 应该是request.size吧
https://github.com/vesoft-inc/nebula-java/blob/63403bce3d42cf836e2b6ca8971fd80364014a06/client/src/main/java/com/vesoft/nebula/client/storage/StorageClientImpl.java#L301

**Comment by critical27** [comment]
groups是涉及到storage机器的数目，发到同一个机器的request会合并
